### ISSUE TITLE
소프트웨어 공학 1조 Damu 조 입니다.

### ISSUE THREAD

**Issue by walloonam** [JongdaeHan/SE2022_HAEA0008_2-#6]
https://github.com/TheDaum/software_Project

**Comment by JongdaeHan** [comment]
주소가 잘못된게 아닌가 싶은데요, 확인 부탁드립니다.

**Comment by JongdaeHan** [comment]
아니면 혹시 private repository로 팠을수도 있고요

**Comment by walloonam** [comment]
public으로 교체했습니다 한번 확인부탁드립니다!
